<!--
The bib chunk below must go last in this document according to how R Markdown renders.  More info is at http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html
-->

<!-- \backmatter -->
<!-- 
If you'd like to change the name of the bibliography to something else,
delete "References" and replace it.
-->

# References {-}
<!--
This manually sets the header for this unnumbered chapter.
-->
<!-- \markboth{References}{References} -->
<!--
To remove the indentation of the first entry.
-->
<!-- \noindent -->

<!--
To create a hanging indent and spacing between entries.  These three lines may need to be removed for styles that don't require the hanging indent.
-->

\setlength{\parindent}{-0.20in}
\setlength{\leftskip}{0.20in}
\setlength{\parskip}{8pt}


<!--
This is just for testing with more citations for the bibliography at the end.  Add other entries into the list here if you'd like them to appear in the bibliography even if they weren't explicitly cited in the document.
-->

<!-- \indent  -->
<!-- \setlength{\parindent}{-0.20in} -->
<!-- \setlength{\leftskip}{0.20in} -->
Abeli, T. et al. 2014. Effects of marginality on plant population performance. - J. Biogeogr. 41: 239–249.\par
Ackerly, D. D. 2003. Community Assembly , Niche Conservatism , and Adaptive Evolution in Changing Environments. - Int. J. Plant Sci. 164: 164–184.\par
Ackerly, D. D. et al. 2010. The geography of climate change: Implications for conservation biogeography. - Divers. Distrib. 16: 476–487.\par
Adler, P. B. et al. 2013. Trait-based tests of coexistence mechanisms. - Ecol. Lett. 16: 1294–1306.\par
AEMET (Spanish Meteorological Agency) 2014. Avance climatológico mensual mes de septiembre 2014 en la Región de Murcia.\par
AEMET (Spanish Meteorological Agency) and IP (Portuguese Meteorological Insitute) 2011. Iberian climate atlas. Air temperature and precipitation (1971-2000) (MR y M Ministerio de Medio Ambiente, Ed.).\par
Aitken, S. N. et al. 2008. Adaptation, migration or extirpation: climate change outcomes for tree populations. - Evol. Appl. 1: 95–111.\par
Alexander, J. M. et al. 2016. When Climate Reshuffles Competitors: A Call for Experimental Macroecology. - Trends Ecol. Evol. 31: 831–841.\par
Allen, C. D. and Breshears, D. D. 1998. Drought-induced shift of a forest – woodland ecotone: Rapid landscape response to climate variation. - Ecology 95: 14839–14842.\par
Allen, C. D. et al. 2010. A global overview of drought and heat-induced tree mortality reveals emerging climate change risks for forests. - For. Ecol. Manage. 259: 660–684.\par
Allen, C. D. et al. 2015. On underestimation of global vulnerability to tree mortality and forest die-off from hotter drought in the Anthropocene. - Ecosphere 6: art129.\par
Anderegg, W. R. L. et al. 2012. The roles of hydraulic and carbon stress in a widespread climate-induced forest die-off. - Proc. Natl. Acad. Sci. 109: 233–237.\par
Anderson, R. P. et al. 2002. Using niche-based GIS modeling to test geographic predictions of competitive exclusion and competitive release in South American pocket mice. - Oikos 98: 3–16.\par
Anne, P. 1945. Carbone organique (total) du sol et de l’humus. - Ann. Agron. 15: 161–172.\par
Araújo, M. B. and Guisan, A. 2006. Five (or so) challenges for species distribution modelling. - J. Biogeogr. 33: 1677–1688.\par
Araújo, M. B. and New, M. 2007. Ensemble forecasting of species distributions. - Trends Ecol. Evol. 22: 42–47.\par
Araújo, M. B. et al. 2013. Heat freezes niche evolution (D Sax, Ed.). - Ecol. Lett. 16: 1206–1219.\par
Araújo, M. B. et al. 2019. Standards for distribution models in biodiversity assessments. - Sci. Adv. 5: eaat4858.\par
Ashraf, M. et al. 2011. Drought Tolerance: Roles of Organic Osmolytes, Growth Regulators, and Mineral Nutrients. - Adv. Agron. 111: 249–296.\par
Austin, M. 1971. The role of regression analysis in plant ecology. - Proc. Ecol. Soc. Aust. 6: 63–75.\par
Austin, M. P. et al. 1990. Measurement of the Realized Qualitative Niche: Environmental Niches of Five Eucalyptus Species. - Ecol. Monogr. 60: 161–177.\par
Barbet-Massin, M. et al. 2012. Selecting pseudo-absences for species distribution models: How, where and how many? - Methods Ecol. Evol. 3: 327–338.\par
Barry, J. P. et al. 1995. Climate-Related, Long-Term Faunal Changes in a California Rocky Intertidal Community. Science. 267: 672–675.\par
Barve, N. et al. 2011. The crucial role of the accessible area in ecological niche modeling and species distribution modeling. - Ecol. Modell. 222: 1810–1819.\par
Belyea, L. R. and Lancaster, J. 1999. Assembly Rules within a Contingent Ecology. - Oikos 86: 402.\par
Benito Garzón, M. et al. 2011. Intra-specific variability and plasticity influence potential tree species distributions under climate change. - Glob. Ecol. Biogeogr. 20: 766–778.\par
Bernard-Verdier, M. et al. 2012. Community assembly along a soil depth gradient: Contrasting patterns of plant trait convergence and divergence in a Mediterranean rangeland (H Cornelissen, Ed.). - J. Ecol. 100: 1422–1433.\par
Bertrand, R. et al. 2012. Disregarding the edaphic dimension in species distribution models leads to the omission of crucial spatial information under climate change: The case of Quercus pubescens in France. - Glob. Chang. Biol. 18: 2648–2660.\par
Bertrand, R. et al. 2016. Ecological constraints increase the climatic debt in forests. - Nat. Commun. 7: 12643.\par
Bigler, C. et al. 2006. Drought as an inciting mortality factor in scots pine stands of the Valais, Switzerland. - Ecosystems 9: 330–343.\par
Blonder, B. et al. 2014. The n-dimensional hypervolume. - Glob. Ecol. Biogeogr. 23: 595–609.\par
Blonder, B. et al. 2015. Linking environmental filtering and disequilibrium to biogeography with a community climate framework. - Ecology 96: 972–985.\par
Blonder, B. et al. 2017. Predictability in community dynamics. - Ecol. Lett. 20: 293–306.\par
Bowler, D. and Böhning-Gaese, K. 2017. Improving the community-temperature index as a climate change indicator. - PLoS One 12: 1–17.\par
Boyce, M. S. et al. 2002. Evaluating resource selection functions. - Ecol. Modell. 157: 281–300.\par
Bramer, I. et al. 2018. Advances in Monitoring and Modelling Climate at Ecologically Relevant Scales. - Adv. Ecol. Res. 58: 101–161.\par
Braun-Blanquet, J. and Bolòs, O. 1957. The plant communities of the Central Ebro Basin and their dynamics. - An. la Estac. Exp. Aula Dei 5: 1–266.\par
Breiner, F. T. et al. 2017. Including environmental niche information to improve IUCN Red List assessments (B Schröder, Ed.). - Divers. Distrib. 23: 484–495.\par
Broennimann, O. and Guisan, A. 2008. Predicting current and future biological invasions: both native and invaded ranges matter. - Biol. Lett. 4: 585–9.\par
Broennimann, O. et al. 2006. Do geographic distribution, niche property and life form explain plants’ vulnerability to global change? - Glob. Chang. Biol. 12: 1079–1093.\par
Broennimann, O. et al. 2012. Measuring ecological niche overlap from occurrence and spatial environmental data. - Glob. Ecol. Biogeogr. 21: 481–497.\par
Brown, J. H. 1984. On the Relationship between Abundance and Distribution of Species. - Am. Nat. 124: 255–279.\par
Cáceres, M. De et al. 2015. Coupling a water balance model with forest inventory data to predict
drought stress: the role of forest structural changes vs. climate changes. - Agric. For.
Meteorol. 213: 77–90.\par
Cadotte, M. W. and Tucker, C. M. 2017. Should Environmental Filtering be Abandoned? - Trends Ecol. Evol. 32: 429–437.\par
Carnicer, J. et al. 2011. Widespread crown condition decline, food web disruption, and amplified tree mortality with increased climate change-type drought. - Proc. Natl. Acad. Sci. U. S. A. 108: 1474–8.\par
Cassel, D. K. and Nielsen, D. R. 1986. Field capacity and available water capacity. - In: Klute, A. (ed), Methods of Soil Analysis: Part 1—Physical and Mineralogical Methods. Agronomy m. Soil Science Society of America, pp. 901–926.\par
Clark, J. D. et al. 1993. A Multivariate Model of Female Black Bear Habitat Use for a Geographic Information System. - J. Wildl. Manage. 57: 519.\par
Colwell, R. K. and Rangel, T. F. 2009. Hutchinson’s duality: the once and future niche. - Proc. Natl. Acad. Sci. U. S. A. 106 Suppl 2: 19651–8.\par
Colwell, R. K. et al. 2008. Global Warming, Elevational Range Shifts, and Lowland Biotic Attrition in the Wet Tropics. Science. 322: 258–261.\par
Cornwell, W. K. and Ackerly, D. D. 2009. Community Assembly and Shifts in Plant Trait Distributions across an Environmental Gradient in Coastal California. - Source Ecol. Monogr. 79.\par
Coumou, D. and Rahmstorf, S. 2012. A decade of weather extremes. - Nat. Clim. Chang. 2: 491–496.\par
Csergő, A. M. et al. 2017. Less favourable climates constrain demographic strategies in plants (J Gurevitch, Ed.). - Ecol. Lett. 20: 969–980.\par
D’Amen, M. et al. 2017. Spatial predictions at the community level: From current approaches to future frameworks. - Biol. Rev. 92: 169–187.\par
Dallas, T. A. and Hastings, A. 2018. Habitat suitability estimated by niche models is largely unrelated to species abundance. - Glob. Ecol. Biogeogr. 27: 1448–1456.\par
Dallas, T. et al. 2017. Species are not most abundant in the centre of their geographic range or climatic niche. - Ecol. Lett. 20: 1526–1533.\par
Davis, M. B. 1986. Climatic Instability, Time, Lags, and Community Disequilibrium.: 269–284.\par
Davis, M. B. and Shaw, R. G. 2001. Range shifts and adaptive responses to quaternary climate change. Science. 292: 673–679.\par
Davis, K. T. et al. 2019. Microclimatic buffering in forests of the future: the role of local water balance. - Ecography (Cop.). 42: 1–11.\par
De Frenne, P. et al. 2013. Microclimate moderates plant responses to macroclimate warming. - Proc. Natl. Acad. Sci. U. S. A. 110: 18561–5.
de la Riva, E. G. et al. 2016a. Leaf Mass per Area (LMA) and Its Relationship with Leaf Structure and Anatomy in 34 Mediterranean Woody Species along a Water Availability Gradient. - PLoS One 11: e0148788.\par
de la Riva, E. G. et al. 2016. Disentangling the relative importance of species occurrence, abundance and intraspecific variability in community assembly: a trait-based approach at the whole-plant level in Mediterranean forests. - Oikos 125: 354–363.\par
de la Riva, E. G. et al. 2017. A Multidimensional Functional Trait Approach Reveals the Imprint of Environmental Stress in Mediterranean Woody Communities. - Ecosystems 21: 248–262.\par
del Cacho, M. and Lloret, F. 2012. Resilience of Mediterranean shrubland to a severe drought episode: The role of seed bank and seedling emergence. - Plant Biol. 14: 458–466.\par
Devictor, V. et al. 2012. Differences in the climatic debts of birds and butterflies at a continental scale. - Nat. Clim. Chang. 2: 121–124.\par
Diaz, S. et al. 1998. Plant functional traits and environmental filters at a regional scale. - J. Veg. Sci. 9: 113–122.\par
Dormann, C. F. 2007. Promising the future? Global change projections of species distributions. - Basic Appl. Ecol. 8: 387–397.\par
Duchaufour, P. 1970. Pédologie (M& Paris, Ed.).\par
Duong, T. 2018. Package “ks”. ks: Kernel Smoothing. in press.\par
Duong, T. and Hazelton, M. L. 2005. Cross-validation bandwidth matrices for multivariate kernel density estimation. - Scand. J. Stat. 32: 485–506.\par
Easterling, D. R. et al. 2000. Climate Extremes: Observations, Modeling, and Impacts. Science. 289: 2068–2074.\par
Elith, J. 2006. Novel methods improve prediction of species’ distributions from occurrence data: Supplement. - Ecography (Cop.). 29: 129–151.\par
Elith, J. and Leathwick, J. R. 2009. Species Distribution Models: Ecological Explanation and Prediction Across Space and Time. - Annu. Rev. Ecol. Evol. Syst. 40: 677–697.\par
Elith, J. and Graham, C. H. 2009. Do they? How do they? WHY do they differ? on finding reasons for differing performances of species distribution models. - Ecography (Cop.). 32: 66–77.\par
Elith, J. et al. 2002. Mapping epistematic uncertainties and vague concepts in predictions of species distribution. - Ecol. Modell. 157: 313–329.\par
Elith, J. et al. 2008. A working guide to boosted regression trees. - J. Anim. Ecol. 77: 802–813.\par
Elith, J. et al. 2010. The art of modelling range-shifting species. - Methods Ecol. Evol. 1: 330–342.\par
Elton, C. S. 1927. Animal ecology. - University of Chicago Press.\par
Esteve-Selma, M. A. et al. 2010. Effects of climatic change on the distribution and conservation of Mediterranean forests: The case of Tetraclinis articulata in the Iberian Peninsula. - Biodivers. Conserv. 19: 3809–3825.\par
Esteve-Selma, M. A. et al. 2015. Cambio climático y biodiversidad en el contexto de la Región de Murcia. - In: Consejería de Agua Agricultura y Medio Ambiente (ed), Cambio climático en la Región de Murcia. Evaluación basada en indicadores. pp. 105–132.\par
Fick, S. E. and Hijmans, R. J. 2017. WorldClim 2: new 1-km spatial resolution climate surfaces for global land areas. - Int. J. Climatol. 37: 4302–4315.\par
Fielding, A. H. and Bell, J. F. 1997. A review of methods for the assessment of prediction errors in conservation presence/absence models. - Environ. Conserv. 24: 38–49.\par
Franklin, J. 2010. Mapping species distributions. Spatial inference and prediction. - Cambridge University Press.\par
Franklin, J. et al. 2013. Modeling plant species distributions under future climates: how fine scale do climate projections need to be? - Glob. Chang. Biol. 19: 473–483.\par
Franklin, J. et al. 2016. Global change and terrestrial plant community dynamics. - Proc. Natl. Acad. Sci. 113: 3725–3734.\par
Franks, S. J. et al. 2014. Evolutionary and plastic responses to climate change in terrestrial plant populations. - Evol. Appl. 7: 123–139.\par
Freckleton, R. P. et al. 2002. Phylogenetic Analysis and Comparative Data: 160: 712–726.\par
Fridley, J. 2009. Downscaling Climate over Complex Terrain: High Finescale (<1000 m) Spatial Variation of Near-Ground Temperatures in a Montane Forested Landscape (Great Smoky Mountains)*. - J. Appl. Meteorol. Climatol. 48: 1033–1049.\par
Fridley, J. D. et al. 2011. Soil heterogeneity buffers community response to climate change in species-rich grassland. - Glob. Chang. Biol. 17: 2002–2011.\par
Galiano, L. et al. 2010. Drought-Induced Multifactor Decline of Scots Pine in the Pyrenees and Potential Vegetation Change by the Expansion of Co-occurring Oak Species. - Ecosystems 13: 978–991.\par
Gause, G. F. 1934. The struggle for existence (Williams & Wilkin, Ed..\par
Gaüzère, P. et al. 2018. Empirical Predictability of Community Responses to Climate Change. - Front. Ecol. Evol. 6: 186.\par
GBIF.org (18 January 2019), GBIF Occurrence Download https://doi.org/10.15468/dl.er7c3e \par
Gee, G. W. and Bauder, J. W. 1986. Particle size analysis. - In: Klute, A. (ed), Methods of Soil Analysis: Part 1—Physical and Mineralogical Methods. Soil Science Society of America, pp. 383–411.\par
Geiger, R. et al. 1995. The Climate Near the Ground. - Vieweg+Teubner Verlag.\par
Giorgi, F. and Lionello, P. 2008. Climate change projections for the Mediterranean region. - Glob. Planet. Change 63: 90–104.\par
Gotelli, N. J. et al. 2010. Macroecological signals of species interactions in the Danish avifauna. - Proc. Natl. Acad. Sci. U. S. A. 107: 5030–5.\par
Graae, B. J. et al. 2018. Stay or go – how topographic complexity influences alpine plant population and community responses to climate change. - Perspect. Plant Ecol. Evol. Syst. 30: 41–50.\par
Graham, C. H. et al. 2004. Integrating phylogenetics and environmental niche models to explore speciation mechanisms in dendrobatid frogs. - Evolution 58: 1781–93.\par
Grant, P. R. et al. 2016. Evolution caused by extreme events. - Philos. Trans. R. Soc. Lond. B. Biol. Sci. 372: 20160146.\par
Greenwood, S. et al. 2017. Tree mortality across biomes is promoted by drought intensity, lower wood density and higher specific leaf area. - Ecol. Lett. 20: 539–553.\par
Grinnell, J. 1917. The Niche-Relationships of the California Thrasher. - Auk 34: 427–433.\par
Guiot, J. and Cramer, W. 2016. Climate change: The 2015 Paris Agreement thresholds and Mediterranean basin ecosystems. Science. 354: 4528–4532.\par
Guisan, A. and Zimmermann, N. E. 2000. Predictive habitat distribution models in ecology. - Ecol. Modell. 135: 147–186.\par
Guisan, A. and Thuiller, W. 2005. Predicting species distribution: Offering more than simple habitat models. - Ecol. Lett. 8: 993–1009.\par
Guisan, A. et al. 2013. Predicting species distributions for conservation decisions (H Arita, Ed.). - Ecol. Lett. 16: 1424–1435.\par
Guisan, A. et al. 2014. Unifying niche shift studies: insights from biological invasions. - Trends Ecol. Evol. 29: 260–269.\par
Guisan, A. et al. 2017. Habitat Suitability and Distribution Models (Cambridge University Press, Ed.). - Cambridge University Press.\par
Guisan, A. et al. 2019. Scaling the linkage between environmental niches and functional traits for improved spatial predictions of biological communities (A Hampe, Ed.). - Glob. Ecol. Biogeogr.: geb.12967.\par
Hamerlynck, E. P. and McAuliffe, J. R. 2008. Soil-dependent canopy die-back and plant mortality in two Mojave Desert shrubs. - J. Arid Environ. 72: 1793–1802.\par
Hampe, A. and Petit, R. J. 2005. Conserving biodiversity under climate change: the rear edge matters. - Ecol. Lett. 8: 461–467.\par
Hanley, A. J. and McNeil, J. B. 1982. The Meaning and Use of the Area under a Receiver Operating Characteristic (ROC) Curve. - Radiology 143: 29–36.\par
Hannah, L. et al. 2007. Protected area needs in a changing climate. - Front. Ecol. Environ. 5: 131–138.\par
Hanski, I. 1999. Metapopulation ecology. - Oxford University Press.\par
Hewitt, G. 2000. The genetic legacy of the Quaternary ice ages. - Nature 405\par
Hijmans, R. J. et al. 2005. Very high resolution interpolated climate surfaces for global land areas. - Int. J. Climatol. 25: 1965–1978.\par
Hijmans, R. J. et al. 2011. Package ‘ dismo .’ - October: 55.\par
Hijmans, A. R. J. et al. 2016. Package ‘ dismo ’ Species Distribution Modeling. - https://cran.r-project.org/web/packages/dismo/dismo.pdf: (accesed 11.01.2016).\par
HilleRisLambers, J. et al. 2012. Rethinking Community Assembly through the Lens of Coexistence Theory. - Annu. Rev. Ecol. Evol. Syst. 43: 227–248.\par
Hirzel, A. H. et al. 2006. Evaluating the ability of habitat suitability models to predict species presences. - Ecol. Modell. 199: 142–152.\par
Holt, R. D. 2009. Bringing the Hutchinsonian niche into the 21st century: Ecological and evolutionary perspectives. - Proc. Natl. Acad. Sci. U. S. A. 106: 19659–19665.\par
Holt, R. D. et al. 2005. Theoretical models of species’ borders: single species approaches. - Oikos 108: 18–27.\par
Hubbell, S. P. 2001. The unified neutral theory of biodiversity and biogeography. - Princeton University Press.\par
Huberty, C. J. 1994. Applied discriminant analysis. - Wiley.\par
Huntley, B. and Webb, T. 1989. Migration: Species’ Response to Climatic Variations Caused by Changes in the Earth’s Orbit. - J. Biogeogr. 16: 5.\par
Hutchinson, G. E. 1957. Concluding Remarks - The Demographic Symposium as a Heterogeneous Unstable Population. 53: 415–427.\par
Hutchinson, G. E. 1978. An introduction to population ecology. - Yale University Press.\par
IPCC Working Group 1 2014. IPCC Fifth Assessment Report (AR5) - The physical science basis (VB and PMM (eds. . Stocker, T.F., D. Qin, G.-K. Plattner, M. Tignor, S.K. Allen, J. Boschung, A. Nauels, Y. Xia, Ed.).\par
IUSS Working Group WRB 2015. World Reference Base for Soil Resources 2014, update 2015. International soil classification system for naming soils and creating legends for soil maps. - World Soil Resour. Reports No. 106.\par
Jackson, S. T. 2009. Introduction. - In: (editor), S. T. J. (ed), Essay on the Geography of Plants. The University of Chicago Press, pp. 1–52.\par
Jackson, S. T. and Sax, D. F. 2010. Balancing biodiversity in a changing environment: extinction debt, immigration credit and species turnover. - Trends Ecol. Evol. 25: 153–160.\par
Jaime, L. et al. 2019. Scots pine (Pinus sylvestris L.) mortality is explained by the climatic suitability of both host tree and bark beetle populations. - For. Ecol. Manage. 448: 119–129.\par
Jentsch, A. et al. 2007. A new generation of events , not trends experiments. - Front. Ecol. Environ. 5: 365–374.\par
Joppa, L. N. et al. 2013. Troubling trends in scientific software use. - Science (80-. ). 340: 814–815.\par
Jump, A. S. and Woodward, F. I. 2003. Seed production and population density decline approaching the range-edge of Cirsium species. - New Phytol. 160: 349–358.\par
Jump, A. S. et al. 2006. Rapid climate change-related growth decline at the southern range edge of Fagus sylvatica. - Glob. Chang. Biol. 12: 2163–2174.\par
Jump, A. S. et al. 2009. The altitude-for-latitude disparity in the range retractions of woody species. - Trends Ecol. Evol. 24: 694–701.\par
Karger, D. N. et al. 2017. Climatologies at high resolution for the earth’s land surface areas. - Sci. Data 4: 170122.\par
Kearney, M. 2006. Habitat , environment and niche: what are we modelling? - Oikos 115: 186–191.\par
Kearney, M. and Porter, W. 2009. Mechanistic niche modelling: Combining physiological and spatial data to predict species’ ranges. - Ecol. Lett. 12: 334–350.\par
Keddy, P. A. 1992. Assembly and response rules: two goals for predictive community ecology. - J. Veg. Sci. 3: 157–164.\par
Kramer, P. J. and Boyer, J. S. 1995. Water relations of plants and soils. - Academic Press.\par
Kreuzwieser, J. and Gessler, A. 2010. Global climate change and tree nutrition: Influence of water availability. - Tree Physiol. 30: 1221–1234.\par
Kreyling, J. et al. 2011. Stochastic trajectories of succession initiated by extreme climatic events. - Ecol. Lett. 14: 758–764.\par
Kruckeberg, A. R. 2002. Geology and plant life: the effects of landforms and rock types on plants. - University of Washington Press.\par
Kuussaari, M. et al. 2009. Extinction debt: a challenge for biodiversity conservation. - Trends Ecol. Evol. 24: 564–571.\par
Kuznetsova, A. et al. 2017. lmerTest Package: Tests in Linear Mixed Effects Models. - J. Stat. Softw. 82: 1–26.\par
Lázaro, R. et al. 2001. Analysis of a 30-year rainfall record (1967–1997) in semi–arid SE Spain for implications on vegetation. - J. Arid Environ. 48: 373–395.\par
Leathwick, J. R. 1998. Are New Zealand’s Nothofagus species in equilibrium with their environment? - J. Veg. Sci. 9: 719–732.\par
Lembrechts, J. J. et al. 2019a. Comparing temperature data sources for use in species distribution models: From in‐situ logging to remote sensing. - Glob. Ecol. Biogeogr.: geb.12974.\par
Lembrechts, J. J. et al. 2019b. Incorporating microclimate into species distribution models. - Ecography (Cop.). 42: 1267–1279.\par
Lenoir, J. and Svenning, J.-C. 2015. Climate-related range shifts - a global multidimensional synthesis and new research directions. - Ecography (Cop.). 38: 15–28.\par
Lenoir, J. et al. 2008. A Significant Upward Shift in Plant Species Optimum Elevation During the 20th Century. Science. 320: 1768–1771.\par
Lenoir, J. et al. 2013. Local temperatures inferred from plant communities suggest strong spatial buffering of climate warming across Northern Europe. - Glob. Chang. Biol. 19: 1470–1481.\par
Lenth, R. V. 2016. Least-Squares Means: The R Package lsmeans. - J. Stat. Softw. 69: 1–33.\par
Lesica, P. and Crone, E. E. 2016. Arctic and boreal plant species decline at their southern range limits in the Rocky Mountains. - Ecol. Lett.: 166–174.\par
Lévesque, M. et al. 2016. Soil nutrients influence growth response of temperate tree species to drought (R Jones, Ed.). - J. Ecol. 104: 377–387.\par
Li, Y. and Shipley, B. 2018. Community divergence and convergence along experimental gradients of stress and disturbance. - Ecology 99: 775–781.\par
Li, Y. et al. 2018. Habitat filtering determines the functional niche occupancy of plant communities worldwide. - J. Ecol. 106: 1001–1009.\par
Lloret, F. and Granzow-de la Cerda, I. 2013. Plant competition and facilitation after extreme drought episodes in Mediterranean shrubland: Does damage to vegetation cover trigger replacement by juniper woodland? - J. Veg. Sci. 24: 1020–1032.\par
Lloret, F. and García, C. 2016. Inbreeding and neighbouring vegetation drive drought-induced die-off within juniper populations. - Funct. Ecol. 30: 1696–1704.\par
Lloret, F. and Kitzberger, T. 2018. Historical and event-based bioclimatic suitability predicts regional forest vulnerability to compound effects of severe drought and bark beetle infestation. - Glob. Chang. Biol. in press.\par
Lloret, F. et al. 2012. Extreme climatic events and vegetation: The role of stabilizing processes. - Glob. Chang. Biol. 18: 797–805.\par
Lloret, F. et al. 2016. Climatic events inducing die-off in Mediterranean shrublands: are species responses related to their functional traits? - Oecologia 180: 961–973.\par
Lomolino, M. V. et al. 2004. Foundations of biogeography: classic papers with commentaries. - University of Chicago Press.\par
Macarthur, R. and Levins, R. 1967. The Limiting Similarity, Convergence, and Divergence of Coexisting Species. - Am. Nat. 101: 377–385.\par
Maestre, F. T. and Cortina, J. 2002. Spatial patterns of surface soil properties and vegetation in a Mediterranean semi-arid steppe. - Plant Soil 241: 279–291.\par
Maggini, R. et al. 2011. Are Swiss birds tracking climate change?: Detecting elevational shifts using response curve shapes. - Ecol. Modell. 222: 21–32.\par
Maguire, B. 1973. Niche Response Structure and the Analytical Potentials of Its Relationship to the Habitat. - Am. Nat. 107: 213–246.\par
Martinez-Meyer, E. et al. 2013. Ecological niche structure and rangewide abundance patterns of species. - Biol. Lett. 9: 20120637–20120637.\par
Martínez-Vilalta, J. and Lloret, F. 2016. Drought-induced vegetation shifts in terrestrial ecosystems: The key role of regeneration dynamics. - Glob. Planet. Change 144: 94–108.\par
Mauri, A. et al. 2016. Pinus halepensis and Pinus brutia in Europe: distribution, habitat, usage and threats. - In: European Atlas of Forest Tree Species. in press.\par
Mauri, A. et al. 2017. EU-Forest, a high-resolution tree occurrence dataset for Europe. - Sci. Data in press.\par
Mcdowell, N. et al. 2008. Mechanisms of Plant Survival and Mortality during Drought: Why Do Some Plants Survive while Others Succumb to Drought? - New Phytol. 178: 719–739.\par
McDowell, N. et al. 2019. Mechanisms of a coniferous woodland persistence under drought and heat. - Environ. Res. Lett. in press.\par
Mellert, K. H. et al. 2011. Hypothesis-driven species distribution models for tree species in the Bavarian Alps. - J. Veg. Sci. 22: 635–646.\par
Merow, C. et al. 2013. A practical guide to MaxEnt for modeling species’ distributions: what it does, and why inputs and settings matter. - Ecography (Cop.). 36: 1058–1069.\par
Merow, C. et al. 2014. What do we gain from simplicity versus complexity in species distribution models? - Ecography (Cop.). 37: 1267–1281.\par
Miriti, M. N. et al. 2007. Episodic death across species of desert shrubs. - Ecology 88: 32–36.\par
Morueta-Holme, N. and Svenning, J.-C. 2018. Geography of Plants in the New World: Humboldt’s Relevance in the Age of Big Data. - Ann. Missouri Bot. Gard. 103: 315–329.\par
Mouillot, F. et al. 2002. Simulating climate change impacts on fire frequency and vegetation dynamics in a Mediterranean ecosystem. - Glob. Chang. Biol. 8: 423–437.\par
Murphy, H. T. et al. 2006. Distribution of abundance across the range in eastern North American trees. - Glob. Ecol. Biogeogr. 15: 63–71.\par
Niehaus, A. C. et al. 2012. Predicting the physiological performance of ectotherms in fluctuating thermal environments. - J. Exp. Biol. 215: 694–701.\par
Ninyerola, M. et al. 2000. A methodological approach of climatological modelling of air temperature and precipitation through GIS techniques. - Int. J. Climatol. 20: 1823–1841.\par
Ninyerola, M. et al. 2007. Monthly precipitation mapping of the Iberian Peninsula using spatial interpolation tools implemented in a Geographic Information System. - Theor. Appl. Climatol. 89: 195–209.\par
Osorio‐Olvera, L. et al. 2019. On population abundance and niche structure. - Ecography (Cop.). 42: 1415–1425.\par
Parmesan, C. 2006. Ecological and Evolutionary Responses to Recent Climate Change. - Annu. Rev. Ecol. Evol. Syst. 37: 637–669.\par
Parmesan, C. and Yohe, G. 2003. A globally coherent fingerprint of climate change impacts across natural systems. - Nature 421: 37–42.\par
Pausas, J. G. and Bond, W. J. 2018. Humboldt and the reinvention of nature. - J. Ecol. in press.\par
Pearman, P. B. et al. 2008. Niche dynamics in space and time. - Trends Ecol. Evol. 23: 149–158.\par
Pearson, R. G. and Dawson, T. P. 2003. Predicting the Impacts of Climate Change on the Distribution of Species: Are Bioclimate Envelope Models Useful? - Glob. Ecol. Biogeogr. 12: 361–371.\par
Pearson, R. G. et al. 2006. Model-based uncertainty in species range prediction. - J. Biogeogr. 33: 1704–1711.\par
Pearson, D. E. et al. 2018. Community Assembly Theory as a Framework for Biological Invasions. - Trends Ecol. Evol. 33: 313–325.\par
Peñuelas, J. et al. 2001. Severe drought effects on mediterranean woody flora in Spain. - For. Sci. 47: 214–218.\par
Pérez-Ramos, I. M. et al. 2017. Climate variability and community stability in Mediterranean shrublands: the role of functional diversity and soil environment. - J. Ecol. 105: 1335–1346.\par
Pérez Navarro, M. Á. et al. 2018. Climatic Suitability Derived from Species Distribution Models Captures Community Responses to an Extreme Drought Episode. - Ecosystems: 1–14.\par
Peterson, A. T. 2011. Ecological Niches and Geographic Distributions (Princeton University Press, Ed.).\par
Peterson, A. T. and Vieglais, D. A. 2001. Predicting Species Invasions Using Ecological Niche Modeling: New Approaches from Bioinformatics Attack a Pressing Problem. - Bioscience 51: 363–371.\par
Petitpierre, B. et al. 2012. Climatic Niche Shifts Are Rare Among Terrestrial Plant Invaders. Science. 335: 1344–1348.\par
Phillips, S. J. and Dudík, M. 2008a. Modeling of species distribution with Maxent: new extensions and a comprehensive evalutation. - Ecography (Cop.). 31: 161–175.\par
Phillips, S. J. and Dudík, M. 2008b. Modeling of species distributions with Maxent: new extensions and a comprehensive evaluation. - Ecography (Cop.). 31: 161–175.\par
Piedallu, C. et al. 2013. Soil water balance performs better than climatic water variables in tree species distribution modelling. - Glob. Ecol. Biogeogr. 22: 470–482.\par
Pironon, S. et al. 2015. Do geographic, climatic or historical ranges differentiate the performance of central versus peripheral populations? - Glob. Ecol. Biogeogr. 24: 611–620.\par
Pironon, S. et al. 2016. Geographic variation in genetic and demographic performance: new insights from an old biogeographical paradigm. - Biol. Rev.: 000–000.\par
Pironon, S. et al. 2017. The ‘Hutchinsonian niche’ as an assemblage of demographic niches: implications for species geographic ranges. - Ecography (Cop.). in press.\par
Porporato, A. et al. 2004. Soil Water Balance and Ecosystem Response to Climate Change. - Am. Nat. 164: 625–632.\par
Prentice, I. C. et al. 1992. A Global Biome Model Based on Plant Physiology and Dominance, Soil Properties and Climate. - J. Biogeogr. 19: 117.\par
Pulliam, H. R. 1988. Sources, Sinks, and Population Regulation. - Am. Nat. 132: 652–661.\par
Pulliam, H. R. 2000. On the relationship between niche and distribution. - Ecol. Lett. 3: 349–361.\par
Randin, C. F. et al. 2009. Climate change and plant distribution: local models predict high-elevation persistence. - Glob. Chang. Biol. 15: 1557–1569.\par
Ricklefs, R. E. 2008. Disintegration of the ecological community. - Am. Nat. 172: 741–750.\par
Rivas-Martínez, S. et al. 2011. Worldwide bioclimatic classification system. - Glob. Geobot. 1: 1–638.\par
Rivas-Martínez, S. et al. 2017. Bioclimatology of the Iberian Peninsula and the Balearic Islands. - In: Springer, Cham, pp. 29–80.\par
Sangüesa-Barreda, G. et al. 2018. Delineating limits: Confronting predicted climatic suitability to field performance in mistletoe populations. - J. Ecol. 106: 2218–2229.\par
Sapes, G. et al. 2017. Species climatic niche explains drought-induced die-off in a Mediterranean woody community. - Ecosphere 8: e01833.\par
Schurr, F. M. et al. 2012. How to understand species’ niches and range dynamics: A demographic research agenda for biogeography. - J. Biogeogr. 39: 2146–2162.\par
Segurado, P. and Araújo, M. B. 2004. An evaluation of methods for modelling species distributions. - J. Biogeogr. 31: 1555–1568.\par
Serra-Diaz, J. M. et al. 2013. Geographical patterns of congruence and incongruence between correlative species distribution models and a process-based ecophysiological growth model. - J. Biogeogr. 40: 1928–19338.\par
Sexton, J. P. et al. 2009. Evolution and Ecology of Species Range Limits. - Annu. Rev. Ecol. Evol. Syst 40: 415–36.\par
Sexton, J. P. et al. 2014. Genetic isolation by environment or distance: which pattern of gene flow is most common? - Evolution. 68: 1–15.\par
Shantz, H. L. 1927. Drought Resistance and Soil Moisture. - Ecology 8: 145–157.\par
Sheffield, J. and Wood, E. F. 2008. Projected changes in drought occurrence under future global warming from multi-model , multi-scenario , IPCC AR4 simulations. - Clim. Dyn. 31: 79–105.\par
Simpson, A. H. et al. 2016. Soil–climate interactions explain variation in foliar, stem, root and reproductive traits across temperate forests. - Glob. Ecol. Biogeogr. 25: 964–978.\par
Soberón, J. 2007. Grinnellian and Eltonian niches and geographic distributions of species. - Ecol. Lett. 10: 1115–1123.\par
Soberón, J. and Nakamura, M. 2009. Niches and distributional areas: Concepts, methods, and assumptions. - Proc. Natl. Acad. Sci. 106: 19645–19650.\par
Solarik, K. A. et al. 2018. Local adaptation of trees at the range margins impacts range shifts in the face of climate change. - Glob. Ecol. Biogeogr. 27: 1507–1519.\par
Suggitt, A. J. et al. 2011. Habitat microclimates drive fine-scale variation in extreme temperatures. - Oikos 120: 1–8.\par
Svenning, J.-C. and Skov, F. 2004. Limited filling of the potential range in European tree species. - Ecol. Lett. 7: 565–573.\par
Svenning, J.-C. and Skov, F. 2007. Could the tree diversity pattern in Europe be generated by postglacial dispersal limitation? - Ecol. Lett. 10: 453–460.\par
Svenning, J. C. and Sandel, B. 2013. Disequilibrium vegetation dynamics under future climate change. - Am. J. Bot. 100: 1266–1286.\par
Takahashi, K. and Tanaka, S. 2016. Relative importance of habitat filtering and limiting similarity on species assemblages of alpine and subalpine plant communities. - J. Plant Res. 129: 1041–1049.\par
Thibault, K. M. and Brown, J. H. 2008. Impact of an extreme climatic event on community assembly. - Proc. Natl. Acad. Sci. 105: 3410–3415.\par
Thomas, C. D. et al. 2004. Extinction risk from climate change. - Nature 427: 145–148.\par
Thornthwaite, C. W. and Mather, J. R. 1957. Instructions and tables for computing potential evapotranspiration and the water balance,. - Publ. Climatol. 10: 185–311.\par
Thuiller, W. 2004. Patterns and uncertainties of species’ range shifts under climate change. - Glob. Chang. Biol. 10: 2020–2027.\par
Thuiller, W. 2013. On the importance of edaphic variables to predict plant species distributions - limits and prospects. - J. Veg. Sci. 24: 591–592.\par
Thuiller, W. et al. 2005a. Niche properties and geographical extent as predictors of species sensitivity to climate change. - Glob. Ecol. Biogeogr. 14: 347–357.\par
Thuiller, W. et al. 2005b. Climate change threats to plant diversity in Europe. - Proc. Natl. Acad. Sci. U. S. A. 102 (23): 8245-8250.\par
Thuiller, W. et al. 2010. Variation in habitat suitability does not always relate to variation in species’ plant functional traits. - Biol. Lett. 6: 120–123.\par
Thuiller, W. et al. 2014. Does probability of occurrence relate to population dynamics? - Ecography (Cop.). 37: 1155–1166.\par
Tulloch, A. I. T. et al. 2016. Conservation planners tend to ignore improved accuracy of modelled species distributions to focus on multiple threats and ecological processes. - Biol. Conserv. 199: 157–171.\par
Ulrich, W. et al. 2014. Climate and soil attributes determine plant species turnover in global drylands. - J. Biogeogr. 41: 2307–2319.\par
Valladares, F. et al. 2004. CAPÍTULO 6 Estrés hídrico: ecofisiología y escalas de la sequía. - In: Valladares, F. (ed), Ecologia del bosque mediterráneo en un mundo cambiante. Ministerio. pp. 163–190.\par
Valladares, F. et al. 2008. Functional traits and phylogeny: What is the main ecological process determining species assemblage in roadside plant communities? - J. Veg. Sci. 19: 381–392.\par
Valladares, F. et al. 2014a. Global change and Mediterranean forests: current impacts and potential responses. - In: Forests and Global Change. pp. 47–75.\par
Valladares, F. et al. 2014b. The effects of phenotypic plasticity and local adaptation on forecasts of species range shifts under climate change. - Ecol. Lett. 17: 1351–1364.\par
van der Maaten, E. et al. 2017. Species distribution models predict temporal but not spatial variation in forest growth. - Ecol. Evol. 7: 2585–2594.\par
van Mantgem, P. J. et al. 2009. Widespread Increase of Tree Mortality Rates in the Western United States. Science. 323: 521–524.\par
VanDerWal, J. et al. 2009. Abundance and the environmental niche: environmental suitability estimated from niche models predicts the upper limit of local abundance. - Am. Nat. 174: 282–91.\par
Vellend, M. 2010. Conceptual synthesis in community ecology. - Q. Rev. Biol. 85: 183–206.\par
Vicente-Serrano, S. M. et al. 2013. Response of vegetation to drought time-scales across global land biomes. - Proc. Natl. Acad. Sci. U. S. A. 110: 52–57.\par
Volterra, V. 1926. Fluctuations in the Abundance of a Species considered Mathematically1. - Nature 118: 558–560.\par
von Humboldt, A. and Bonpland, A. 1807 (2009). Essay on the geography of plants. Reprint, translated by Sylvie Romanowski, edited with an introduction by S. T. Jackson. The University of Chicago Press.\par
Walther, G.-R. et al. 2009. Alien species in a warmer world: risks and opportunities. - Trends Ecol. Evol. 24: 686–693.\par
Wan, Z. 2008. New refinements and validation of the MODIS Land-Surface Temperature/Emissivity products. - Remote Sens. Environ. 112: 59–74.\par
Wan, Z. et al. 2015. MOD11C2 MODIS/Terra Land Surface Temperature/Emissivity 8‐Day L3 Global 0.05° CMG V006 [Data set]. In NASA EOSDIS LP DAAC.\par
Wang, J. and Maintainer, L. S. C. 2016. Package “MixRF.” in press.\par
Webb, T. 1986. Is vegetation in equilibrium with climate? How to interpret late-Quaternary pollen data. - Vegetatio 67: 75–91.\par
Webb, C. O. and Donoghue, M. J. 2005. Phylomatic: Tree assembly for applied phylogenetics. - Mol. Ecol. Notes 5: 181–183.\par
Webb III, T. 1992. Global Changes During the Last 3 Million Years: Climatic Controls and Biotic Responses. - Annu. Rev. eclogy Syst. 23: 141–173.\par
Weber, M. M. et al. 2016. Is there a correlation between abundance and environmental suitability derived from ecological niche modelling? A meta-analysis. - Ecography (Cop.). 40: 817–828.\par
Weiher, E. et al. 2011. Advances, challenges and a developing synthesis of ecological community assembly theory. - Philos. Trans. R. Soc. B Biol. Sci. 366: 2403–2413.\par
Wessels, K. J. et al. 1998. An evaluation of the gradsect biological survey method. - Biodivers. Conserv. 7: 1093–1121.\par
Wiens, J. J. and Graham, C. H. 2005. Niche Conservatism: Integrating Evolution, Ecology, and Conservation Biology. - Annu. Rev. Ecol. Evol. Syst. 36: 519–539.\par
Wiens, J. A. et al. 2009. Niches, models, and climate change: Assessing the assumptions and uncertainties. - Proc. Natl. Acad. Sci. 106: 19729–19736.\par
Woodward, F. I. 1987. Climate and plant distribution. - Cambridge University Press.\par
Wright, J. W. et al. 2006. Experimental verification of ecological niche modeling in a heterogeneous environment. - Ecology 87: 2433–2439.\par
Zavaleta, E. S. et al. 2003. Grassland Responses To Three Years of Elevated Temperature, Co 2 , Precipitation, and N Deposition. - Ecol. Monogr. 73: 585–604.\par
Zimmermann, N. E. et al. 2009. Climatic extremes improve predictions of spatial patterns of tree species. - Proc. Natl. Acad. Sci. U. S. A. 106 Suppl: 19723–8.\par
Zunzunegui, M. et al. 2005. To live or to survive in Doñana dunes: Adaptive responses of woody species under a Mediterranean climate. - Plant Soil 273: 77–89.\par


