treatments <- c(
  'NA',
  "None",
  # "Irrigated",
  "distructive sampling, understory management",
  "Girdling early successional",
  "Control",                                                                                           
  # "postmortality",                                                                                     
  "1Premortality",                                                                        
  "Ambient Control",
  "fertilization at plantation",
  # "ELEVATED CO2 treatments maintained at 550 ppm",
  "AMBIENT CO2 FACE rings",
  # "Post-thinning",
  "Reference",
  "Before thinning",
  # "After thinning",
  # "drought",
  "control",
  "none, only periodict thinning opérations every 5-6 years that remove  20 to 25% of basal area",
  # "Thinning",
  # "100irrigationneeds",
  # "45irrigationneeds",
  # "LM2 Nitrogen and Phoporous fertilized",
  # "Commercial hedgerow olive orchard. See Lopez-Bernal et al. (2015, Irrig. Sci.) for further details",
  "non_thinned",
  # "thinned",
  # 'Irrigation',
  "Pre-thinning",
  # "Elevated atmospheric CO2",
  # "moderate severity fire",
  # "high severity fire",
  # "TPF - Thinned, pruned, fertilised",
  # "TP0 - Thinned, pruned, unfertilised",
  # "T0F - Thinned, unpruned, fertilised"
  "Control - Unthinned, unpruned, unfertilised",
  # "0PF - Unthinned, pruned, fertilised",
  # "0P0 - Unthinned, pruned, unfertilised", 
  "AcaciaMonoculture",
  "MixtureEucalyptusAndAcacia",
  "EucalyptusMonoculture",
  "2premortality",
  "AMBIENT CO2 FACE rings",
  # "After_Thinning",                                                                                    
  "Pre Irrigation",                                                                                    
  "Before Thinning",                                                                                   
  "natural conditions",                                                                                
  # "00F - Unthinned, unpruned, fertilised",                                                             
  # "T00 - Thinned, unpruned, unfertilised",                                                             
  # "LM1 Nitrogen fertilization",                                                                        
  # "Post Irrigation",                                                                                   
  "Radiation Level"
  # "Extrem thinning",                                                                                   
  # "Medium thinning",                                                                                   
  # "Low thinning",
  # "Af1",
  # "Af2"
)
